### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by udaysk3**
Fixed Issue #10

### CODE REVIEW

**Comment by udaysk3** [comment]
Please also add the hacktoberfest-accepted label to this after merging

**Comment by teamhashed-admin** [comment]
Thanks

**Comment by udaysk3** [comment]
Can you add the label hacktoberfest-accepted to this pull request. So that it gets counted for hacktoberfest2023

**Comment by whoismaruf** [comment]
Hi @udaysk3 thanks for the PR. Well, we are inviting you to add/modify a few changes to this repo with your own ideas. I appreciate your effort. ✨

**Comment by udaysk3** [comment]
Sure I will be contributing to it. Can you mention any other issues or shall I play around with it?

**Pull request merged**
